make the compiler happy
Depending on build flags the compiler complains:

ykfde.c:307:3: error: ignoring return value of ‘getrandom’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]

Let's add the return value to `len`, which is no longer used anyway.

Fixes #33